# Generated by Django 5.2.4 on 2025-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_birth_date_member_emai_member_gener_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='gener',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
